name: NoFoodPM
main: NurAzliYT\NoFoodPM\NoFoodPM
version: 0.0.1
api: 5.0.0
author: NurAzliYT, NurAzli, DavyCraft648
description: Feels like you are fasting
website: https://github.com/DavyCraft648/NoFood
permissions:
  nofoods.bypass:
    description: Allow player to eat
    default: true
